[package]
name = "webservervice-starter"
version = "0.1.0"
authors = ["Andrea Prearo <andrea.prearo@gmail.com>"]

[dependencies]
rocket = "*"
rocket_contrib = "*"
rocket_codegen = "*"
serde = "*"
serde_derive = "*"
